#Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
